name: run_tracker
description: 'Run tracker mobile app'
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_map: ^7.0.2
  flutter_map_geojson: ^1.0.8
  flutter_riverpod: ^2.5.1
  fpdart: ^1.1.0
  cupertino_icons: ^1.0.8
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  geolocator: ^13.0.1
  latlong2: ^0.9.1
  streaming_shared_preferences: ^2.0.0
  shared_preferences: ^2.3.2
  universal_platform: ^1.0.0+1
  circular_countdown_timer: ^0.2.4
  flutter_foreground_task: ^8.9.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  app_settings: ^5.1.1
  json_annotation: ^4.9.0
  intl: ^0.19.0
  get_it: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  hive_generator: ^2.0.1
  json_serializable: ^6.8.0
  mockito: ^5.2.2

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/